### ISSUE TITLE
Upcoming Features - Reference List tracker

### ISSUE THREAD

**Issue by ghiscoding** [ghiscoding/aurelia-slickgrid#31]
### Upcoming, missing, incomplete or simply a wish list feature

- Grid State & Grid Presets
   - [ ] Support Custom Interface instead of currently fixed interface, see [SO Question](https://stackoverflow.com/questions/49122204/how-to-use-dynamic-object-properties-in-typescript/49122307#49122307)
- Export to File
   - [ ] Export to Excel using [ExcelBuilder](https://www.npmjs.com/package/excel-builder), see [UI Grid demo](http://ui-grid.info/docs/#!/tutorial/410_excel_exporting_data_and_header) and [UI Grid code](https://github.com/angular-ui/ui-grid/commit/dc7d7733b3989eba372d4e912b0d3189b59d23ca#diff-45ebf47632603fb37765ea8912a14185)

#### Completed Features
- Controls / Plugins
   - [x] Remote Model (AJAX) Plugin - (ref PR #115)
   - [x] Grid Menu (aka hamburger menu)
   - [x] Row Move Manager Plugin (ref #110)
   - [x] Header Menu Plugin
   - [x] Column Picker
   - [x] Column Header Button Plugin
   - [x] Column Header Menu Plugin
       - [x] Add "hide column" command in menu, driven by the ControlAndPlugin Service
       - [x] Add "sort" ASC/DESC command in menu, driven by the ControlAndPlugin Service
   - [x] Row Detail Panel, see [SlickGrid demo](http://6pac.github.io/SlickGrid/examples/example16-row-detail.html) - (PR #113)
- Editors
   - [x] Date Editor (with Flatpickr)
   - [x] Long Text with Textarea
   - [x] Input
   - [x] Multiple Select / Single Select
   - [x] Custom Editor
   - [x] Slider Editor
   - [x] Undo Functionality
   - [x] Dependencies Injection (DI) in Editors (ref #25)
   - [x] MultipleSelect & SingleSelect Editor should be able to render sanitized HTML (ref #87)
   - [x] Editor Collection Async load and collection changes should refresh select dropdown (ref #83)
- Filters 
   - [x] Input
   - [x] Multiple Select / Single Select
   - [x] Custom Filter
   - [x] Compound Input Filters (ref #26)
   - [x] Compound Date Filters (ref #26)
   - [x] Compound Slider (ref #79)
   - [x] Slider filter (ref #79)
   - [x] MultipleSelect & SingleSelect Filter should be able to render sanitized HTML (ref #87)
   - [x] Filter Collection Async load and collection changes should refresh select dropdown (ref #83)
   - [x] Compound Input Filter should support multiple input type, not only `text` but also `number`, 
   - [x] Datalist Filter (issue #17 / see PR #122)`password` (PR #117)
   - [x] Input Mask Filter (see PR #132)
- [x] Copy & Paste like Excel, see [SlickGrid demo](http://6pac.github.io/SlickGrid/examples/example-excel-compatible-spreadsheet.html)
- [x] Support single & multi-columns with numbering icons and tri-state option, see [SlickGrid demo](http://6pac.github.io/SlickGrid/examples/example-multi-column-tristate-numbered-sort.html)
- [x] Colspan, see [SlickGrid demo](http://6pac.github.io/SlickGrid/examples/example-colspan.html)
- [x] Column Header Grouping colspan, see [SlickGrid demo](http://6pac.github.io/SlickGrid/examples/example-column-group.html)
- Export to File
   - [x] Export to CSV
   - [x] Export to text file with any separator type
- Grid State & Grid Presets
   - [x] Current Filters
   - [x] Current Sorters
   - [x] Current Pagination (Backend Service)
   - [x] Current Column Visibility (show/hide state) (ref #67)
   - [x] Current Column position order (ref #67)
- Grouping
   - [x] Grouping and Aggregate (ref #37), see [SlickGrid demo](http://6pac.github.io/SlickGrid/examples/example-grouping.html)
   - [x] Grouping by Column Dragging, see [SlickGrid demo](http://6pac.github.io/SlickGrid/examples/example-draggable-grouping.html) - (PR #114)
- [x] Support i18n accross the lib
- [x] Grid Auto-resize
- [x] Row Selection
- [x] Dynamically add or change Column Definitions (ref #57)
- [x] Multiple Grid in 1 View (ref #36)
- [x] Support latest Bootstrap 4
- [x] Pinned (frozen) Columns/Rows (see PR #121)

**Comment by ghiscoding** [comment]
If anyone wants to contribute to this project, you are free to take any of the unchecked item(s) and create a PR (Pull Request).

This list includes most of the `SlickGrid` features, but it doesn't mean that they will all be addressed. This is an Open Source project and contributions are more then welcome. Maybe one day, this list will be all checked out. :)

**Comment by ghiscoding** [comment]
Closing as there is only 1 remaining feature in this list (Export to Excel) and I will track it in the [v2.x](https://github.com/ghiscoding/aurelia-slickgrid/projects/3) Project instead
